[build]
  publish = "dist"
  command = "npm install --include=dev && CI='' npm run build:netlify"
  ignore_warnings = true

[build.environment]
  NODE_ENV = "production"
  VITE_APP_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css" 